### PR TITLE
Allowing arrays to contain arrays and objects

### PR DESCRIPTION
**Pull request by bmalinconico**
Arrays of Arrays or Arrays of Objects are valid HCL syntax (or at least in the TF version we are using.

This PR adds support for objects and arrays inside arrays

### CODE REVIEW

**Comment by bmalinconico** [comment]
@mfcastellani any concerns nwith this change?

**Comment by metmajer** [comment]
@mfcastellani is this project still maintained?

**Comment by mfcastellani** [comment]
Hi Martin, yes.

I was travelling and will take a look today.

Sorry for long delay.



Em qui, 14 de fev de 2019 10:00, Martin Etmajer <notifications@github.com
escreveu:

**Review by mfcastellani — APPROVED** [review]

**Comment by metmajer** [comment]
Thanks, @mfcastellani, this helps a ton!

**Comment by metmajer** [comment]
@mfcastellani please don't forget to craft a release as well. Cheers!

**Comment by mfcastellani** [comment]
Version 1.1.0 released right now. Thank you @bmalinconico and @metmajer 

Closing this issue

**Pull request merged**
